INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('1', 'artistic-swimming', 'Duet', 'artistic-swimming', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('2', 'artistic-swimming', 'Team', 'artistic-swimming', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('3', 'diving', 'Women''s 3m Springboard', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('4', 'diving', 'Women''s 10m Platform', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('5', 'diving', 'Women''s Synchronised 3m Springboard', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('6', 'diving', 'Women''s Synchronised 10m Platform', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('7', 'diving', 'Men''s 3m Springboard', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('8', 'diving', 'Men''s 10m Platform', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('9', 'diving', 'Men''s Synchronised 3m Springboard', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('10', 'diving', 'Men''s Synchronised 10m Platform', 'diving', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('11', 'marathon-swimming', 'Women''s 10km', 'marathon-swimming', 'Pont Alexandre III');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('12', 'marathon-swimming', 'Men''s 10km', 'marathon-swimming', 'Pont Alexandre III');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('13', 'surfing', 'Men', 'surfing', 'Teahupo''o, Tahiti');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('14', 'surfing', 'Women', 'surfing', 'Teahupo''o, Tahiti');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('15', 'swimming', 'Women''s 50m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('16', 'swimming', 'Women''s 100m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('17', 'swimming', 'Women''s 200m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('18', 'swimming', 'Women''s 400m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('19', 'swimming', 'Women''s 800m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('20', 'swimming', 'Women''s 1500m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('21', 'swimming', 'Women''s 100m Backstroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('22', 'swimming', 'Women''s 200m Backstroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('23', 'swimming', 'Women''s 100m Breaststroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('24', 'swimming', 'Women''s 200m Breaststroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('25', 'swimming', 'Women''s 100m Butterfly', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('26', 'swimming', 'Women''s 200m Butterfly', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('27', 'swimming', 'Women''s 200m Individual Medley', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('28', 'swimming', 'Women''s 400m Individual Medley', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('29', 'swimming', 'Women''s 4 x 100m Freestyle Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('30', 'swimming', 'Women''s 4 x 200m Freestyle Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('31', 'swimming', 'Women''s 4 x 100m Medley Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('32', 'swimming', 'Men''s 50m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('33', 'swimming', 'Men''s 100m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('34', 'swimming', 'Men''s 200m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('35', 'swimming', 'Men''s 400m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('36', 'swimming', 'Men''s 800m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('37', 'swimming', 'Men''s 1500m Freestyle', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('38', 'swimming', 'Men''s 100m Backstroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('39', 'swimming', 'Men''s 200m Backstroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('40', 'swimming', 'Men''s 100m Breaststroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('41', 'swimming', 'Men''s 200m Breaststroke', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('42', 'swimming', 'Men''s 100m Butterfly', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('43', 'swimming', 'Men''s 200m Butterfly', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('44', 'swimming', 'Men''s 200m Individual Medley', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('45', 'swimming', 'Men''s 400m Individual Medley', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('46', 'swimming', 'Men''s 4 x 100m Freestyle Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('47', 'swimming', 'Men''s 4 x 200m Freestyle Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('48', 'swimming', 'Men''s 4 x 100m Medley Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('49', 'swimming', 'Mixed 4 x 100m Medley Relay', 'swimming', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('50', 'water-polo', 'Men', 'water-polo', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('51', 'water-polo', 'Men', 'water-polo', 'Paris La Defense Arena');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('52', 'water-polo', 'Women', 'water-polo', 'Aquatics Centre');
INSERT INTO Event (Event_ID, Event_Tag, Event_Name, Discipline_Code, Venue) VALUES ('53', 'water-polo', 'Women', 'water-polo', 'Paris La Defense Arena');
