INSERT INTO Country (Country_code, Country_name) VALUES ('DMA', 'Dominica');
INSERT INTO Country (Country_code, Country_name) VALUES ('HUN', 'Hungary');
INSERT INTO Country (Country_code, Country_name) VALUES ('USA', 'United States');
INSERT INTO Country (Country_code, Country_name) VALUES ('GRE', 'Greece');
INSERT INTO Country (Country_code, Country_name) VALUES ('GAB', 'Gabon');
INSERT INTO Country (Country_code, Country_name) VALUES ('SRB', 'Serbia');
INSERT INTO Country (Country_code, Country_name) VALUES ('LAO', 'Laos');
INSERT INTO Country (Country_code, Country_name) VALUES ('NEP', 'Nepal');
INSERT INTO Country (Country_code, Country_name) VALUES ('AUS', 'Australia');
INSERT INTO Country (Country_code, Country_name) VALUES ('CHN', 'China');
INSERT INTO Country (Country_code, Country_name) VALUES ('FRA', 'France');
INSERT INTO Country (Country_code, Country_name) VALUES ('CRC', 'Costa Rica');
INSERT INTO Country (Country_code, Country_name) VALUES ('CAN', 'Canada');
INSERT INTO Country (Country_code, Country_name) VALUES ('POR', 'Portugal');
INSERT INTO Country (Country_code, Country_name) VALUES ('ITA', 'Italy');
INSERT INTO Country (Country_code, Country_name) VALUES ('BDI', 'Burundi');
INSERT INTO Country (Country_code, Country_name) VALUES ('LTU', 'Lithuania');
INSERT INTO Country (Country_code, Country_name) VALUES ('CRO', 'Croatia');
INSERT INTO Country (Country_code, Country_name) VALUES ('CHI', 'Chile');
INSERT INTO Country (Country_code, Country_name) VALUES ('SOL', 'Solomon Islands');
INSERT INTO Country (Country_code, Country_name) VALUES ('ARG', 'Argentina');
INSERT INTO Country (Country_code, Country_name) VALUES ('EGY', 'Egypt');
INSERT INTO Country (Country_code, Country_name) VALUES ('MNE', 'Montenegro');
INSERT INTO Country (Country_code, Country_name) VALUES ('UKR', 'Ukraine');
INSERT INTO Country (Country_code, Country_name) VALUES ('KSA', 'Saudi Arabia');
INSERT INTO Country (Country_code, Country_name) VALUES ('KOR', 'South Korea');
INSERT INTO Country (Country_code, Country_name) VALUES ('DEN', 'Denmark');
INSERT INTO Country (Country_code, Country_name) VALUES ('BAH', 'Bahamas');
INSERT INTO Country (Country_code, Country_name) VALUES ('JPN', 'Japan');
INSERT INTO Country (Country_code, Country_name) VALUES ('AIN', 'Anguilla');
INSERT INTO Country (Country_code, Country_name) VALUES ('NCA', 'Nicaragua');
INSERT INTO Country (Country_code, Country_name) VALUES ('PER', 'Peru');
INSERT INTO Country (Country_code, Country_name) VALUES ('HKG', 'Hong Kong');
INSERT INTO Country (Country_code, Country_name) VALUES ('NIG', 'Niger');
INSERT INTO Country (Country_code, Country_name) VALUES ('AUT', 'Austria');
INSERT INTO Country (Country_code, Country_name) VALUES ('NED', 'Netherlands');
INSERT INTO Country (Country_code, Country_name) VALUES ('SRI', 'Sri Lanka');
INSERT INTO Country (Country_code, Country_name) VALUES ('JAM', 'Jamaica');
INSERT INTO Country (Country_code, Country_name) VALUES ('MAR', 'Morocco');
INSERT INTO Country (Country_code, Country_name) VALUES ('GBR', 'United Kingdom');
INSERT INTO Country (Country_code, Country_name) VALUES ('YEM', 'Yemen');
INSERT INTO Country (Country_code, Country_name) VALUES ('BRA', 'Brazil');
INSERT INTO Country (Country_code, Country_name) VALUES ('NZL', 'New Zealand');
INSERT INTO Country (Country_code, Country_name) VALUES ('ESP', 'Spain');
INSERT INTO Country (Country_code, Country_name) VALUES ('SUI', 'Switzerland');
INSERT INTO Country (Country_code, Country_name) VALUES ('CGO', 'Congo');
INSERT INTO Country (Country_code, Country_name) VALUES ('GER', 'Germany');
INSERT INTO Country (Country_code, Country_name) VALUES ('TLS', 'Timor-Leste');
INSERT INTO Country (Country_code, Country_name) VALUES ('IRL', 'Ireland');
INSERT INTO Country (Country_code, Country_name) VALUES ('RSA', 'South Africa');
INSERT INTO Country (Country_code, Country_name) VALUES ('GEO', 'Georgia');
INSERT INTO Country (Country_code, Country_name) VALUES ('COL', 'Colombia');
INSERT INTO Country (Country_code, Country_name) VALUES ('ZAM', 'Zambia');
INSERT INTO Country (Country_code, Country_name) VALUES ('ISR', 'Israel');
INSERT INTO Country (Country_code, Country_name) VALUES ('ANG', 'Anguilla');
INSERT INTO Country (Country_code, Country_name) VALUES ('MAS', 'Malaysia');
INSERT INTO Country (Country_code, Country_name) VALUES ('CAM', 'Cameroon');
INSERT INTO Country (Country_code, Country_name) VALUES ('POL', 'Poland');
INSERT INTO Country (Country_code, Country_name) VALUES ('MAW', 'Malawi');
INSERT INTO Country (Country_code, Country_name) VALUES ('SEN', 'Senegal');
INSERT INTO Country (Country_code, Country_name) VALUES ('PRK', 'North Korea');
INSERT INTO Country (Country_code, Country_name) VALUES ('ISL', 'Iceland');
INSERT INTO Country (Country_code, Country_name) VALUES ('DOM', 'Dominican Republic');
INSERT INTO Country (Country_code, Country_name) VALUES ('CUB', 'Cuba');
INSERT INTO Country (Country_code, Country_name) VALUES ('MEX', 'Mexico');
INSERT INTO Country (Country_code, Country_name) VALUES ('SWE', 'Sweden');
INSERT INTO Country (Country_code, Country_name) VALUES ('FIN', 'Finland');
INSERT INTO Country (Country_code, Country_name) VALUES ('SLO', 'Slovenia');
INSERT INTO Country (Country_code, Country_name) VALUES ('SGP', 'Singapore');
INSERT INTO Country (Country_code, Country_name) VALUES ('PLW', 'Palau');
INSERT INTO Country (Country_code, Country_name) VALUES ('UGA', 'Uganda');
INSERT INTO Country (Country_code, Country_name) VALUES ('PAN', 'Panama');
INSERT INTO Country (Country_code, Country_name) VALUES ('COM', 'Comoros');
INSERT INTO Country (Country_code, Country_name) VALUES ('BEL', 'Belgium');
INSERT INTO Country (Country_code, Country_name) VALUES ('ALB', 'Albania');
INSERT INTO Country (Country_code, Country_name) VALUES ('TUR', 'Turkey');
INSERT INTO Country (Country_code, Country_name) VALUES ('BUR', 'Burkina Faso');
INSERT INTO Country (Country_code, Country_name) VALUES ('PAK', 'Pakistan');
INSERT INTO Country (Country_code, Country_name) VALUES ('ROU', 'Romania');
INSERT INTO Country (Country_code, Country_name) VALUES ('SUR', 'Suriname');
