INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2AUS01', 'Australia', 'M', 'AUS', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2CAN01', 'Canada', 'M', 'CAN', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2CHN01', 'People''s Republic of China', 'M', 'CHN', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2FRA01', 'France', 'M', 'FRA', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2GBR01', 'Great Britain', 'M', 'GBR', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2GER01', 'Germany', 'M', 'GER', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2MEX01', 'Mexico', 'M', 'MEX', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM10MTEAM2UKR01', 'Ukraine', 'M', 'UKR', 'diving', 'Men''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-CHN01', 'People''s Republic of China', 'M', 'CHN', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-ESP01', 'Spain', 'M', 'ESP', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-FRA01', 'France', 'M', 'FRA', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-GBR01', 'Great Britain', 'M', 'GBR', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-ITA01', 'Italy', 'M', 'ITA', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-MEX01', 'Mexico', 'M', 'MEX', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-UKR01', 'Ukraine', 'M', 'UKR', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVM3MTEAM2-USA01', 'United States of America', 'M', 'USA', 'diving', 'Men''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2CAN01', 'Canada', 'W', 'CAN', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2CHN01', 'People''s Republic of China', 'W', 'CHN', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2FRA01', 'France', 'W', 'FRA', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2GBR01', 'Great Britain', 'W', 'GBR', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2MEX01', 'Mexico', 'W', 'MEX', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2PRK01', 'Democratic People''s Republic of Korea', 'W', 'PRK', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2UKR01', 'Ukraine', 'W', 'UKR', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW10MTEAM2USA01', 'United States of America', 'W', 'USA', 'diving', 'Women''s Synchronised 10m Platform');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-AUS01', 'Australia', 'W', 'AUS', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-CHN01', 'People''s Republic of China', 'W', 'CHN', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-FRA01', 'France', 'W', 'FRA', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-GBR01', 'Great Britain', 'W', 'GBR', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-GER01', 'Germany', 'W', 'GER', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-ITA01', 'Italy', 'W', 'ITA', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-UKR01', 'Ukraine', 'W', 'UKR', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('DIVW3MTEAM2-USA01', 'United States of America', 'W', 'USA', 'diving', 'Women''s Synchronised 3m Springboard');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---AUS01', 'Australia', 'W', 'AUS', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---AUT01', 'Austria', 'W', 'AUT', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---CAN01', 'Canada', 'W', 'CAN', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---CHN01', 'People''s Republic of China', 'W', 'CHN', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---EGY01', 'Egypt', 'W', 'EGY', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---ESP01', 'Spain', 'W', 'ESP', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---FRA01', 'France', 'W', 'FRA', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---GBR01', 'Great Britain', 'W', 'GBR', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---GRE01', 'Greece', 'W', 'GRE', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---ISR01', 'Israel', 'W', 'ISR', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---ITA01', 'Italy', 'W', 'ITA', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---JPN01', 'Japan', 'W', 'JPN', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---KOR01', 'Republic of Korea', 'W', 'KOR', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---MEX01', 'Mexico', 'W', 'MEX', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---NED01', 'Netherlands', 'W', 'NED', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---NZL01', 'New Zealand', 'W', 'NZL', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---UKR01', 'Ukraine', 'W', 'UKR', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM2---USA01', 'United States of America', 'W', 'USA', 'artistic-swimming', 'Duet');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---AUS01', 'Australia', 'O', 'AUS', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---CAN01', 'Canada', 'O', 'CAN', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---CHN01', 'People''s Republic of China', 'O', 'CHN', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---EGY01', 'Egypt', 'O', 'EGY', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---ESP01', 'Spain', 'O', 'ESP', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---FRA01', 'France', 'O', 'FRA', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---ITA01', 'Italy', 'O', 'ITA', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---JPN01', 'Japan', 'O', 'JPN', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---MEX01', 'Mexico', 'O', 'MEX', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWAWTEAM8---USA01', 'United States of America', 'O', 'USA', 'artistic-swimming', 'Team');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRAUS01', 'Australia', 'M', 'AUS', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRBRA01', 'Brazil', 'M', 'BRA', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRCAN01', 'Canada', 'M', 'CAN', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRCHN01', 'People''s Republic of China', 'M', 'CHN', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRESP01', 'Spain', 'M', 'ESP', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRFRA01', 'France', 'M', 'FRA', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRGBR01', 'Great Britain', 'M', 'GBR', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRGER01', 'Germany', 'M', 'GER', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRGRE01', 'Greece', 'M', 'GRE', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRHUN01', 'Hungary', 'M', 'HUN', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRISR01', 'Israel', 'M', 'ISR', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRITA01', 'Italy', 'M', 'ITA', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRPOL01', 'Poland', 'M', 'POL', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRSRB01', 'Serbia', 'M', 'SRB', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRSWE01', 'Sweden', 'M', 'SWE', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MFRUSA01', 'United States of America', 'M', 'USA', 'swimming', 'Men''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDAUS01', 'Australia', 'M', 'AUS', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDAUT01', 'Austria', 'M', 'AUT', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDCAN01', 'Canada', 'M', 'CAN', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDCHN01', 'People''s Republic of China', 'M', 'CHN', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDESP01', 'Spain', 'M', 'ESP', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDFRA01', 'France', 'M', 'FRA', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDGBR01', 'Great Britain', 'M', 'GBR', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDGER01', 'Germany', 'M', 'GER', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDIRL01', 'Ireland', 'M', 'IRL', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDITA01', 'Italy', 'M', 'ITA', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDJPN01', 'Japan', 'M', 'JPN', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDKOR01', 'Republic of Korea', 'M', 'KOR', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDNED01', 'Netherlands', 'M', 'NED', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDPOL01', 'Poland', 'M', 'POL', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDSUI01', 'Switzerland', 'M', 'SUI', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X100MMDUSA01', 'United States of America', 'M', 'USA', 'swimming', 'Men''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRAUS01', 'Australia', 'M', 'AUS', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRBRA01', 'Brazil', 'M', 'BRA', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRCAN01', 'Canada', 'M', 'CAN', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRCHN01', 'People''s Republic of China', 'M', 'CHN', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRESP01', 'Spain', 'M', 'ESP', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRFRA01', 'France', 'M', 'FRA', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRGBR01', 'Great Britain', 'M', 'GBR', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRGER01', 'Germany', 'M', 'GER', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRGRE01', 'Greece', 'M', 'GRE', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRISR01', 'Israel', 'M', 'ISR', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRITA01', 'Italy', 'M', 'ITA', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRJPN01', 'Japan', 'M', 'JPN', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRKOR01', 'Republic of Korea', 'M', 'KOR', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRLTU01', 'Lithuania', 'M', 'LTU', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRSUI01', 'Switzerland', 'M', 'SUI', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMM4X200MFRUSA01', 'United States of America', 'M', 'USA', 'swimming', 'Men''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRAUS01', 'Australia', 'W', 'AUS', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRBRA01', 'Brazil', 'W', 'BRA', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRCAN01', 'Canada', 'W', 'CAN', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRCHN01', 'People''s Republic of China', 'W', 'CHN', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRDEN01', 'Denmark', 'W', 'DEN', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRFRA01', 'France', 'W', 'FRA', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRGBR01', 'Great Britain', 'W', 'GBR', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRHKG01', 'Hong Kong, China', 'W', 'HKG', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRHUN01', 'Hungary', 'W', 'HUN', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRIRL01', 'Ireland', 'W', 'IRL', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRITA01', 'Italy', 'W', 'ITA', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRNED01', 'Netherlands', 'W', 'NED', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRPOL01', 'Poland', 'W', 'POL', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRSLO01', 'Slovenia', 'W', 'SLO', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRSWE01', 'Sweden', 'W', 'SWE', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MFRUSA01', 'United States of America', 'W', 'USA', 'swimming', 'Women''s 4 x 100m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDAUS01', 'Australia', 'W', 'AUS', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDCAN01', 'Canada', 'W', 'CAN', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDCHN01', 'People''s Republic of China', 'W', 'CHN', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDDEN01', 'Denmark', 'W', 'DEN', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDFRA01', 'France', 'W', 'FRA', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDGBR01', 'Great Britain', 'W', 'GBR', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDGER01', 'Germany', 'W', 'GER', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDHKG01', 'Hong Kong, China', 'W', 'HKG', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDIRL01', 'Ireland', 'W', 'IRL', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDITA01', 'Italy', 'W', 'ITA', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDJPN01', 'Japan', 'W', 'JPN', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDNED01', 'Netherlands', 'W', 'NED', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDPOL01', 'Poland', 'W', 'POL', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDSGP01', 'Singapore', 'W', 'SGP', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDSWE01', 'Sweden', 'W', 'SWE', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X100MMDUSA01', 'United States of America', 'W', 'USA', 'swimming', 'Women''s 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRAUS01', 'Australia', 'W', 'AUS', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRBRA01', 'Brazil', 'W', 'BRA', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRCAN01', 'Canada', 'W', 'CAN', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRCHN01', 'People''s Republic of China', 'W', 'CHN', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRESP01', 'Spain', 'W', 'ESP', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRFRA01', 'France', 'W', 'FRA', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRGBR01', 'Great Britain', 'W', 'GBR', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRGER01', 'Germany', 'W', 'GER', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRHUN01', 'Hungary', 'W', 'HUN', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRISR01', 'Israel', 'W', 'ISR', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRITA01', 'Italy', 'W', 'ITA', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRJPN01', 'Japan', 'W', 'JPN', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRNED01', 'Netherlands', 'W', 'NED', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRNZL01', 'New Zealand', 'W', 'NZL', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRTUR01', 'Türkiye', 'W', 'TUR', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMW4X200MFRUSA01', 'United States of America', 'W', 'USA', 'swimming', 'Women''s 4 x 200m Freestyle Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDAUS01', 'Australia', 'X', 'AUS', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDBRA01', 'Brazil', 'X', 'BRA', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDCAN01', 'Canada', 'X', 'CAN', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDCHN01', 'People''s Republic of China', 'X', 'CHN', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDFRA01', 'France', 'X', 'FRA', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDGBR01', 'Great Britain', 'X', 'GBR', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDGER01', 'Germany', 'X', 'GER', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDGRE01', 'Greece', 'X', 'GRE', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDISR01', 'Israel', 'X', 'ISR', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDITA01', 'Italy', 'X', 'ITA', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDJPN01', 'Japan', 'X', 'JPN', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDKOR01', 'Republic of Korea', 'X', 'KOR', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDNED01', 'Netherlands', 'X', 'NED', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDPOL01', 'Poland', 'X', 'POL', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDSWE01', 'Sweden', 'X', 'SWE', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('SWMX4X100MMDUSA01', 'United States of America', 'X', 'USA', 'swimming', 'Mixed 4 x 100m Medley Relay');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T000180168080', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T005092223144', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T005105061005', 'Netherlands', 'W', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T005106100046', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T006235228185', 'Australia', 'X', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T007165029113', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T009051173051', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T009172220247', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T010112120160', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T010239039210', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T011230232205', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T012092132149', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T012123222150', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T013046016056', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T015155079200', 'South Africa', 'M', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T015237038062', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T017210105197', 'Poland', 'M', 'POL', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T018050143120', 'Republic of Korea', 'M', 'KOR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T018078205011', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T021139183156', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T021182047086', 'Italy', 'W', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T026007161153', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T027137076094', 'Russian Federation', 'X', 'RUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T028003209106', 'Israel', 'W', 'ISR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T031089020226', 'Austria', 'M', 'AUT', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T032180102004', 'Hungary', 'W', 'HUN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T032230089255', 'South Africa', 'W', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T032254243215', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T033016104132', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T034172017177', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T036184251139', 'Canada', 'W', 'CAN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T037217050165', 'Great Britain', 'W', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T040023042051', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T040026171031', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T040052215176', 'Netherlands', 'W', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T041030033135', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T044178085196', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T047173034031', 'Republic of Korea', 'M', 'KOR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T048127108097', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T048252009004', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T050018234251', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T050113048223', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T051001088214', 'South Africa', 'M', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T051044143211', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T053127170146', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T054085034000', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T054095068175', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T055237149192', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T056152082134', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T056184065059', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T056243084219', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T057153235207', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T059049008124', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T061066235178', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T061199228210', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T062099173126', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T070176182065', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T070224246047', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T072239007015', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T073212219121', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T074215096235', 'South Africa', 'X', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T075047206000', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T075068011152', 'Canada', 'W', 'CAN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T076077236018', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T077028246213', 'Canada', 'W', 'CAN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T077146100097', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T079248110012', 'Italy', 'W', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T080064149056', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T080216244244', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T082101210032', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T083202023196', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T083223008017', 'German Democratic Republic', 'W', 'GDR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T083238094200', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T084165231039', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T085109095203', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T085178047216', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T086166153118', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T087049051255', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T087095040064', 'Hungary', 'W', 'HUN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T088121127206', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T091046074070', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T091074019200', 'Australia', 'X', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T093018155227', 'Spain', 'M', 'ESP', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T094207118201', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T094231202250', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T095071193182', 'Hungary', 'M', 'HUN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T096245183145', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T097024201207', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T097190080234', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T097198068021', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T099012198163', 'France', 'M', 'FRA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T103009064164', 'Serbia', 'M', 'SRB', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T104147084217', 'Unified Team', 'M', 'EUN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T107073074055', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T107081146202', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T107144046005', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T108070151074', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T108160233061', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T108161120062', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T109237041237', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T110180116243', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T112130234068', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T112173189178', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T114143077091', 'Sweden', 'W', 'SWE', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T117235076051', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T119034156000', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T120121050150', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T121068205168', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T123093085163', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T124043035021', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T126209096140', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T127073218087', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T127075108220', 'South Africa', 'W', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T127127130200', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T128043238071', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T129222111254', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T133048054128', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T134130092240', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T134149068080', 'Netherlands', 'M', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T135144033254', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T136232070138', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T137153163006', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T138230063185', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T139082206031', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T140007067165', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T140176027011', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T141135060156', 'Germany', 'W', 'GER', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T143157012191', 'New Zealand', 'W', 'NZL', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T144159001066', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T144224053168', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T144247061115', 'Canada', 'M', 'CAN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T145195042022', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T146196227215', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T146250208081', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T147031123022', 'Greece', 'M', 'GRE', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T147237182130', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T150192020010', 'Russian Federation', 'W', 'RUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T150208041031', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T151104038079', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T151165203059', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T151248169221', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T152007104101', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T152072158000', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T153072139060', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T154252007135', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T155251247033', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T156038232203', 'Brazil', 'W', 'BRA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T156096141213', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T157141039174', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T159085242241', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T159170064046', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T160254050136', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T161191071133', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T163062069251', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T163072084245', 'Israel', 'X', 'ISR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T163127098077', 'Poland', 'W', 'POL', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T164107208177', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T164201023192', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T164227030087', 'Poland', 'W', 'POL', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T165150246048', 'France', 'M', 'FRA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T165219065158', 'German Democratic Republic', 'W', 'GDR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T165230053108', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T165255017046', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T170011107055', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T172050237073', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T173034009013', 'Federal Republic of Germany', 'M', 'FRG', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T176081239160', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T176106184236', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T176208225219', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T176255250242', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T177099104150', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T177131070058', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T177162067254', 'Australia', 'X', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T177215118232', 'People''s Republic of China', 'M', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T178131014059', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T179016191120', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T180005075132', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T180082238036', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T182013107120', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T183042211129', 'Netherlands', 'M', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T183209174099', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T184186134220', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T185128006082', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T185180078216', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T186035252019', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T186102254129', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T186119241049', 'New Zealand', 'W', 'NZL', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T187154083112', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T188255247159', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T189119064069', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T190092002110', 'Denmark', 'W', 'DEN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T190186209138', 'Great Britain', 'W', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T193026024173', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T196095020070', 'Lithuania', 'M', 'LTU', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T196196115151', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T197028067226', 'Republic of Korea', 'M', 'KOR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T197064043186', 'France', 'M', 'FRA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T197121211099', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T197192199178', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T200208094172', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T204026223054', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T204027239107', 'South Africa', 'W', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T204216145015', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T207042251035', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T210060000005', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T210070222027', 'South Africa', 'M', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T211255218208', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T212055046088', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T216012230223', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T216014106137', 'South Africa', 'M', 'RSA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T216092071169', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T217151129191', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T217177120018', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T218022032195', 'Russian Federation', 'M', 'RUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T218038013073', 'Netherlands', 'W', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T220064210078', 'Canada', 'W', 'CAN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T221144098126', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T221255160105', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T224085015032', 'Australia', 'X', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T225095247005', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T226131186151', 'Australia', 'M', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T226159240093', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T227166195031', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T227227075171', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T228006119010', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T228010157078', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T228211081171', 'Germany', 'W', 'GER', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T231142178065', 'United States of America', 'X', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T231254107028', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T232052083063', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T234067164063', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T236149232187', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T237004209070', 'Russian Federation', 'M', 'RUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T239108182176', 'Netherlands', 'W', 'NED', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T240229054098', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T241054177157', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T241211162236', 'Italy', 'M', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T241222252249', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T242075099067', 'Great Britain', 'M', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T243153023105', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T243187227111', 'Australia', 'W', 'AUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T244008189081', 'Serbia', 'M', 'SRB', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T244157063110', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T245049147179', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T245225170159', 'Italy', 'W', 'ITA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T245241122029', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T246010078220', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T246234046059', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T247150124139', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T249015074213', 'Great Britain', 'X', 'GBR', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T249049140097', 'People''s Republic of China', 'X', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T249066122070', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T251084043155', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T251234141132', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T251237025181', 'People''s Republic of China', 'W', 'CHN', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T253093211118', 'Russian Federation', 'M', 'RUS', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T254025182131', 'Germany', 'W', 'GER', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T254078068205', 'United States of America', 'W', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('T255047189153', 'United States of America', 'M', 'USA', 'swimming', NULL);
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---AUS01', 'Australia', 'M', 'AUS', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---CRO01', 'Croatia', 'M', 'CRO', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---ESP01', 'Spain', 'M', 'ESP', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---FRA01', 'France', 'M', 'FRA', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---GRE01', 'Greece', 'M', 'GRE', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---HUN01', 'Hungary', 'M', 'HUN', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---ITA01', 'Italy', 'M', 'ITA', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---JPN01', 'Japan', 'M', 'JPN', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---MNE01', 'Montenegro', 'M', 'MNE', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---ROU01', 'Romania', 'M', 'ROU', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---SRB01', 'Serbia', 'M', 'SRB', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOMTEAM7---USA01', 'United States of America', 'M', 'USA', 'water-polo', 'Men');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---AUS01', 'Australia', 'W', 'AUS', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---CAN01', 'Canada', 'W', 'CAN', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---CHN01', 'People''s Republic of China', 'W', 'CHN', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---ESP01', 'Spain', 'W', 'ESP', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---FRA01', 'France', 'W', 'FRA', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---GRE01', 'Greece', 'W', 'GRE', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---HUN01', 'Hungary', 'W', 'HUN', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---ITA01', 'Italy', 'W', 'ITA', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---NED01', 'Netherlands', 'W', 'NED', 'water-polo', 'Women');
INSERT INTO Team (Team_Code, Team_Name, Team_Gender, Country_Code, Discipline_Code, Event_Tag) VALUES ('WPOWTEAM7---USA01', 'United States of America', 'W', 'USA', 'water-polo', 'Women');
