INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1908375', 'Rachel', 'FATTAL', 'Female', 'USA', 'WPOWTEAM7---USA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954602', 'Maria', 'PATRA', 'Female', 'GRE', 'WPOWTEAM7---GRE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1956426', 'Milos', 'CUK', 'Male', 'SRB', 'WPOMTEAM7---SRB01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1941321', 'Boglarka', 'NESZMELY', 'Female', 'HUN', 'WPOWTEAM7---HUN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955943', 'Margo', 'KUO', 'Female', 'AUS', 'SWAWTEAM8---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945222', 'Yaqi', 'KONG', 'Female', 'CHN', 'SWMW4X200MFRCHN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909285', 'Guillaume', 'GUTH', 'Male', 'FRA', 'SWMM4X100MFRFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1967158', 'Patrick', 'HUSSEY', 'Male', 'CAN', 'SWMM4X200MFRCAN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925653', 'Francesco', ' FULVIO', 'Male', 'ITA', 'WPOMTEAM7---ITA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909299', 'Yohann', 'BROUARD', 'Male', 'FRA', 'SWMM4X100MMDFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909299', 'Yohann', 'BROUARD', 'Male', 'FRA', 'SWMX4X100MMDFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'SWMM4X100MMDUSA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'SWMX4X100MMDUSA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'T119034156000', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'T133048054128', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'T160254050136', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'T231142178065', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1935901', 'Nic', 'FINK', 'Male', 'USA', 'T247150124139', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945230', 'Yujie', 'CHENG', 'Female', 'CHN', 'SWMW4X100MFRCHN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1888365', 'Farida', 'ABDELBARY', 'Female', 'EGY', 'SWAWTEAM8---EGY01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925814', 'Claudia Roberta', 'MARLETTA', 'Female', 'ITA', 'WPOWTEAM7---ITA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955940', 'Georgia', 'GARDINER', 'Female', 'AUS', 'SWAWTEAM8---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1568446', 'Aljosa', 'MACIC', 'Male', 'MNE', 'WPOMTEAM7---MNE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897468', 'Anna', 'PYSMENSKA', 'Female', 'UKR', 'DIVW3MTEAM2-UKR01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909243', 'Lison', 'NOWACZYK', 'Female', 'FRA', 'SWMW4X100MFRFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901612', 'Sunwoo', 'HWANG', 'Male', 'KOR', 'SWMM4X100MMDKOR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901612', 'Sunwoo', 'HWANG', 'Male', 'KOR', 'SWMM4X200MFRKOR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901612', 'Sunwoo', 'HWANG', 'Male', 'KOR', 'T018050143120', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901612', 'Sunwoo', 'HWANG', 'Male', 'KOR', 'T047173034031', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901612', 'Sunwoo', 'HWANG', 'Male', 'KOR', 'T197028067226', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954662', 'Nikolaos', 'GKILLAS', 'Male', 'GRE', 'WPOMTEAM7---GRE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1893076', 'Julie Ke', 'JENSEN', 'Female', 'DEN', 'SWMW4X100MFRDEN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1893076', 'Julie Ke', 'JENSEN', 'Female', 'DEN', 'T190092002110', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925665', 'Nicholas', 'PRESCIUTTI', 'Male', 'ITA', 'WPOMTEAM7---ITA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891719', 'Mashiro', 'YASUNAGA', 'Female', 'JPN', 'SWAWTEAM8---JPN01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1943045', 'Calista', 'LIU', 'Female', 'USA', 'SWAWTEAM8---USA01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1906434', 'Mehdi', 'MARZOUKI', 'Male', 'FRA', 'WPOMTEAM7---FRA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1568289', 'Dejan', 'LAZOVIC', 'Male', 'MNE', 'WPOMTEAM7---MNE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946159', 'Bronte', 'CAMPBELL', 'Female', 'AUS', 'SWMW4X100MFRAUS01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945166', 'Xuwei', 'PENG', 'Female', 'CHN', 'T172050237073', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925686', 'Filippo', 'MEGLI', 'Male', 'ITA', 'SWMM4X200MFRITA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925686', 'Filippo', 'MEGLI', 'Male', 'ITA', 'T050018234251', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925686', 'Filippo', 'MEGLI', 'Male', 'ITA', 'T170011107055', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1902493', 'Alexis', 'JANDARD', 'Male', 'FRA', 'DIVM3MTEAM2-FRA01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1947504', 'Blake', 'EDWARDS', 'Male', 'AUS', 'WPOMTEAM7---AUS01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1968857', 'Brigitte', 'SLEEKING', 'Female', 'NED', 'WPOWTEAM7---NED01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1947546', 'Zoe', 'ARANCINI', 'Female', 'AUS', 'WPOWTEAM7---AUS01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1565166', 'Bernhard', 'REITSHAMMER', 'Male', 'AUT', 'SWMM4X100MMDAUT01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1565166', 'Bernhard', 'REITSHAMMER', 'Male', 'AUT', 'T031089020226', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1942736', 'Vanda', 'VALYI', 'Female', 'HUN', 'WPOWTEAM7---HUN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1941141', 'Dora', 'LEIMETER', 'Female', 'HUN', 'WPOWTEAM7---HUN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1915769', 'Luka', 'BUKIC', 'Male', 'CRO', 'WPOMTEAM7---CRO01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1972523', 'Maaike', ' WAARD', 'Female', 'NED', 'SWMW4X100MMDNED01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1893067', 'Elisabeth Sabroe', 'EBBESEN', 'Female', 'DEN', 'SWMW4X100MFRDEN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1893067', 'Elisabeth Sabroe', 'EBBESEN', 'Female', 'DEN', 'SWMW4X100MMDDEN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954371', 'Maria Fernanda', 'COSTA', 'Female', 'BRA', 'SWMW4X200MFRBRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901545', 'Hongchan', 'QUAN', 'Female', 'CHN', 'DIVW10MTEAM2CHN01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1939996', 'Laticia-Leigh', 'TRANSOM', 'Female', 'NZL', 'SWMW4X200MFRNZL01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954879', 'Martin', 'FAMERA', 'Male', 'ESP', 'WPOMTEAM7---ESP01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946201', 'Lani', 'PALLISTER', 'Female', 'AUS', 'SWMW4X200MFRAUS01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954841', 'Ferran', 'JULIA TOUS', 'Male', 'ESP', 'SWMM4X200MFRESP01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1907175', 'Laura', 'RIEDEMANN', 'Female', 'GER', 'SWMW4X100MMDGER01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954614', 'Stylianos', 'ARGYROPOULOS KANAKAKIS', 'Male', 'GRE', 'WPOMTEAM7---GRE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1888861', 'Hana', 'HIEKAL', 'Female', 'EGY', 'SWAWTEAM2---EGY01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1888861', 'Hana', 'HIEKAL', 'Female', 'EGY', 'SWAWTEAM8---EGY01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1543303', 'Max', ' CUSKER', 'Male', 'IRL', 'SWMM4X100MMDIRL01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1956434', 'Radoslav', 'FILIPOVIC', 'Male', 'SRB', 'WPOMTEAM7---SRB01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954343', 'Guilherme', 'SANTOS', 'Male', 'BRA', 'SWMM4X100MFRBRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1962582', 'Rebecca', 'MEDER', 'Female', 'RSA', 'T032230089255', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1962582', 'Rebecca', 'MEDER', 'Female', 'RSA', 'T127075108220', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1962582', 'Rebecca', 'MEDER', 'Female', 'RSA', 'T204027239107', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1565171', 'Eirini-Marina', 'ALEXANDRI', 'Female', 'AUT', 'SWAWTEAM2---AUT01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1959136', 'Kate', 'MILLER', 'Female', 'CAN', 'DIVW10MTEAM2CAN01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1888980', 'Nadine', 'BARSOUM', 'Female', 'EGY', 'SWAWTEAM2---EGY01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1888980', 'Nadine', 'BARSOUM', 'Female', 'EGY', 'SWAWTEAM8---EGY01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1908350', 'Alex', 'BOWEN', 'Male', 'USA', 'WPOMTEAM7---USA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925638', 'Benedetta', 'PILATO', 'Female', 'ITA', 'SWMW4X100MMDITA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1906412', 'Emil', 'BJORCH', 'Male', 'FRA', 'WPOMTEAM7---FRA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897309', 'Anastasia', 'GORBENKO', 'Female', 'ISR', 'SWMW4X200MFRISR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897309', 'Anastasia', 'GORBENKO', 'Female', 'ISR', 'SWMX4X100MMDISR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897309', 'Anastasia', 'GORBENKO', 'Female', 'ISR', 'T028003209106', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897309', 'Anastasia', 'GORBENKO', 'Female', 'ISR', 'T163072084245', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909314', 'Antoine', 'VIQUERAT', 'Male', 'FRA', 'SWMX4X100MMDFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1901539', 'Yani', 'CHANG', 'Female', 'CHN', 'DIVW3MTEAM2-CHN01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925644', 'Giovanni', 'TOCCI', 'Male', 'ITA', 'DIVM3MTEAM2-ITA01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955948', 'Raphaelle', 'GAUTHIER', 'Female', 'AUS', 'SWAWTEAM8---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903540', 'Alexander', 'COHOON', 'Male', 'GBR', 'SWMM4X100MFRGBR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1902960', 'Adam', 'JASZO', 'Male', 'HUN', 'SWMM4X100MFRHUN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1902960', 'Adam', 'JASZO', 'Male', 'HUN', 'T095071193182', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891652', 'Katsuhiro', 'MATSUMOTO', 'Male', 'JPN', 'SWMM4X100MMDJPN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891652', 'Katsuhiro', 'MATSUMOTO', 'Male', 'JPN', 'SWMM4X200MFRJPN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'SWMW4X100MFRAUS01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'SWMW4X100MMDAUS01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T048127108097', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T054085034000', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T056184065059', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T070176182065', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T088121127206', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T094207118201', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T151165203059', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946212', 'Meg', 'HARRIS', 'Female', 'AUS', 'T164201023192', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1968860', 'Maartje', 'KEUNING', 'Female', 'NED', 'WPOWTEAM7---NED01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1879462', 'Adela', 'PISKORSKA', 'Female', 'POL', 'SWMW4X100MMDPOL01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1879462', 'Adela', 'PISKORSKA', 'Female', 'POL', 'T164227030087', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1908381', 'Amanda', 'LONGAN', 'Female', 'USA', 'WPOWTEAM7---USA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891648', 'Naoki', 'MIZUNUMA', 'Male', 'JPN', 'SWMM4X100MMDJPN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1980116', 'Jin Mi', 'JO', 'Female', 'PRK', 'DIVW10MTEAM2PRK01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925667', 'Alessandro', 'VELOTTO', 'Male', 'ITA', 'WPOMTEAM7---ITA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1941119', 'Rita', 'KESZTHELYI', 'Female', 'HUN', 'WPOWTEAM7---HUN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1906443', 'Pierre-Frederic', 'VANPEPERSTRAETE', 'Male', 'FRA', 'WPOMTEAM7---FRA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954791', 'Adrian', 'ABADIA', 'Male', 'ESP', 'DIVM3MTEAM2-ESP01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903759', 'Anastasia', 'BAYANDINA', 'Female', 'FRA', 'SWAWTEAM2---FRA01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903759', 'Anastasia', 'BAYANDINA', 'Female', 'FRA', 'SWAWTEAM8---FRA01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1908359', 'Drew', 'HOLLAND', 'Male', 'USA', 'WPOMTEAM7---USA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955942', 'Kiera', 'GAZZARD', 'Female', 'AUS', 'SWAWTEAM2---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955942', 'Kiera', 'GAZZARD', 'Female', 'AUS', 'SWAWTEAM8---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945149', 'Changhao', 'WANG', 'Male', 'CHN', 'SWMM4X100MMDCHN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945149', 'Changhao', 'WANG', 'Male', 'CHN', 'T117235076051', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945149', 'Changhao', 'WANG', 'Male', 'CHN', 'T123093085163', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1945149', 'Changhao', 'WANG', 'Male', 'CHN', 'T177215118232', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1897751', 'Nina', 'BROWN', 'Female', 'NZL', 'SWAWTEAM2---NZL01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1972527', 'Tessa', 'GIELE', 'Female', 'NED', 'SWMW4X100MFRNED01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1972527', 'Tessa', 'GIELE', 'Female', 'NED', 'SWMW4X100MMDNED01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1972527', 'Tessa', 'GIELE', 'Female', 'NED', 'SWMX4X100MMDNED01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1956444', 'Dusan', 'MANDIC', 'Male', 'SRB', 'WPOMTEAM7---SRB01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1977717', 'Nils', 'LIESS', 'Male', 'SUI', 'SWMM4X100MMDSUI01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1977717', 'Nils', 'LIESS', 'Male', 'SUI', 'SWMM4X200MFRSUI01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1572556', 'Bjoern', 'SEELIGER', 'Male', 'SWE', 'SWMM4X100MFRSWE01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954798', 'Nicolas', 'GARCIA BOISSIER', 'Male', 'ESP', 'DIVM3MTEAM2-ESP01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891710', 'Mitsuru', 'TAKATA', 'Male', 'JPN', 'WPOMTEAM7---JPN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891713', 'Ayano', 'SHIMADA', 'Female', 'JPN', 'SWAWTEAM8---JPN01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1572548', 'Sophie', 'HANSSON', 'Female', 'SWE', 'SWMW4X100MMDSWE01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1572548', 'Sophie', 'HANSSON', 'Female', 'SWE', 'T114143077091', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1980115', 'Mi Rae', 'KIM', 'Female', 'PRK', 'DIVW10MTEAM2PRK01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909315', 'W. Amazigh', 'YEBBA', 'Male', 'FRA', 'SWMM4X100MFRFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909315', 'W. Amazigh', 'YEBBA', 'Male', 'FRA', 'SWMM4X200MFRFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1947498', 'Alice', 'WILLIAMS', 'Female', 'AUS', 'WPOWTEAM7---AUS01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'SWMM4X100MFRITA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'SWMM4X100MMDITA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'T075047206000', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'T108070151074', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'T121068205168', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'T186102254129', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1925636', 'Alessandro', 'MIRESSI', 'Male', 'ITA', 'T241211162236', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1940414', 'Maddison', 'KEENEY', 'Female', 'AUS', 'DIVW3MTEAM2-AUS01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1902491', 'Jules', 'BOUYER', 'Male', 'FRA', 'DIVM3MTEAM2-FRA01', 'diving');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1972528', 'Silke', 'HOLKENBORG', 'Female', 'NED', 'SWMW4X200MFRNED01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1535854', 'En Yi Letitia', 'SIM', 'Female', 'SGP', 'SWMW4X100MMDSGP01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1909253', 'Lucile', 'TESSARIOL', 'Female', 'FRA', 'SWMW4X200MFRFRA01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903762', 'Ambre', 'ESNAULT', 'Female', 'FRA', 'SWAWTEAM8---FRA01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1967138', 'Yuri', 'KISIL', 'Male', 'CAN', 'SWMM4X100MFRCAN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1947531', 'Milos', 'MAKSIMOVIC', 'Male', 'AUS', 'WPOMTEAM7---AUS01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1967389', 'Axelle', 'CREVIER', 'Female', 'CAN', 'WPOWTEAM7---CAN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1906396', 'Louise', 'GUILLET', 'Female', 'FRA', 'WPOWTEAM7---FRA01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1942541', 'Natasa', 'RYBANSKA', 'Female', 'HUN', 'WPOWTEAM7---HUN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1946185', 'Zac', 'COOK', 'Male', 'AUS', 'SWMX4X100MMDAUS01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1891702', 'Kiyomu', 'DATE', 'Male', 'JPN', 'WPOMTEAM7---JPN01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'SWMW4X100MFRGBR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'SWMX4X100MMDGBR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T048252009004', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T050113048223', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T056152082134', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T091046074070', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T109237041237', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T126209096140', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T176255250242', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903557', 'Anna', 'HOPKIN', 'Female', 'GBR', 'T241222252249', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1568434', 'Jovan', 'VUJOVIC', 'Male', 'MNE', 'WPOMTEAM7---MNE01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954819', 'Blanca', 'TOLEDANO LAUT', 'Female', 'ESP', 'SWAWTEAM8---ESP01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'SWMM4X200MFRGBR01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T056152082134', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T080064149056', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T091046074070', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T107081146202', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T109237041237', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T112173189178', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T126209096140', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T159085242241', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T176255250242', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T184186134220', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T193026024173', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T241222252249', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1903552', 'James', 'GUY', 'Male', 'GBR', 'T242075099067', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1967144', 'Lorne', 'WIGGINTON', 'Male', 'CAN', 'SWMM4X200MFRCAN01', 'swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1556227', 'Eduard', 'DRAGUSIN', 'Male', 'ROU', 'WPOMTEAM7---ROU01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1954894', 'Pili', 'PENA', 'Female', 'ESP', 'WPOWTEAM7---ESP01', 'water-polo');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955939', 'Rayna', 'BUCKLE', 'Female', 'AUS', 'SWAWTEAM2---AUS01', 'artistic-swimming');
INSERT INTO Athlete (Athlete_Code, First_Name, Last_Name, Gender, Country_Code, Team_Code, Discipline_Code) VALUES ('1955939', 'Rayna', 'BUCKLE', 'Female', 'AUS', 'SWAWTEAM8---AUS01', 'artistic-swimming');
